##### **CLASS EXERCISE**

##1. Add up the following operands by adding the values alone as well as assigning the values to a variable.

(a) 45, 56, 79

In [ ]:
#Adding the values
45+56+79

180

In [ ]:
#Assigning the values to a variable
a=45
b=56
c=79
#summing the variables of the values
sum= a+b+c
print(sum)

180

(b) 100, 350, 1285

In [ ]:
#Adding values

100 +350+ 1285

1735

In [ ]:
#Assigning values to the variables
a=100
b=350
c=1285
#Summing the variables of the values
sum= a+b+c
print(sum)

1735

(c) 70, 30

In [ ]:
#Adding the values
70+30

100

In [ ]:
#Assigning the values to the variables
a=70
b=30
#Summing the variables of the values
sum= a+b
print(sum)

100

##2. Subtracting the following operands from each other.

(a) 756-987

In [ ]:
#Subtracting the operands from each other

756-987

-231

 (b) 349-50

In [ ]:
#Subtracting the operands from each other

349- 50

299

(c) 23-17

In [ ]:
#Assigning the operants to variables
a=23
b=17

#Subtracting the variables of the operands from each other
print(a-b)

6

##3. What is 15 to the power of 4?

In [ ]:
# Finding the power of the  first operand to the power of the second.

#Assigning the each operants to its variable
x=15
y=4
#Determine the exponentiation of the first operand raised to the power of the second.
print(x**y)

50625

##4. What is the modulus of 67 divided by 18?

In [ ]:
#Assigning each operant to its variable
x= 67
y=18
#Finding the modulus of the first operants by the second operants
print(x%y)

13

##5. Are the division of "36 and 6" the same as their floor division? If no, state your reason.

The asnswer is No, because when using the division operator the answer will always return the quotient as a float whereas when using the floor division,the answer will always return the value of the floor of the quotient, without returning a float value.

######Please refer to the example below:

In [ ]:
#Using the division operator
36/6
# The division operator returns the quotient as a float.
#The result include the decimal

6.0

In [ ]:
#Using the floor division
36//6
#The floor division return the quotient without returning the float value
# Any decimal place is discarded

6

##6. The values that an operator act on are called _____________?

Answer: Operants

##7. Is x==5 the same as x=5? If no, state your reason

No, The (==) used to compare the equality of two values, either alone or assigned to variables whereas "=" is used to assign a value to a variable.

######Please see example below:

In [ ]:
#Using the "=="
x==5
#The answer return as False, because "x" is not equal to "5"

False

In [ ]:
#Using the "="
x=5
print(x)
#The answer return as 5, because we are assigned a variable to a value

5

##8. Can the subtraction operator act on a string value?

No, the subtraction operator (-) cannot directly act on string values in Python. Attempting to subtract one string from another will result in a TypeError.
######Please refer to the example below

In [ ]:
x= "hello"
y= "world"
result = x- y
print(result)
# This will raise a TypeError

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [1]:
x= "hello"
y= "world"
result = x+" "+ y
print(result)

hello world